/**
 * Standard Error Codes for SafeOps
 */
const ErrorCodes = {
  CLOUD_NOT_CONNECTED: 'CLOUD_NOT_CONNECTED',
  CREDENTIAL_EXPIRED: 'CREDENTIAL_EXPIRED',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  TERMINATION_FAILED: 'TERMINATION_FAILED',
  BILLING_DISABLED: 'BILLING_DISABLED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  CLOUD_ONBOARDING_FAILED: 'CLOUD_ONBOARDING_FAILED'
};

module.exports = ErrorCodes;
